name: the_next_big_thing

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.9.0
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.5
  google_fonts: ^6.3.1
  firebase_crashlytics: ^5.0.1
  font_awesome_flutter: ^10.10.0
  intl: ^0.20.2
  flutter_offline: ^5.0.0
  device_info_plus: ^11.5.0
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  pin_code_fields: ^8.0.1
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/